apiVersion: v1
kind: Pod
metadata:
  name: multipod
  labels:
    name: multipod
spec:
  containers:
    - name: producer
      image: ubuntu
      command:
        - "/bin/bash"
      args:
        - "-c"
        - "while true; do echo $(hostname) $(date) >> /var/log/index.html; sleep 10; done"
      volumeMounts:
        - mountPath: /var/log
          name: webcontent
    - name: consumer
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: webcontent
  volumes:
    - name: webcontent
      emptyDir: {}
