apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  selector:
    app: backend
    type: flask
    version: v1
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flask-node
spec:
  type: NodePort
  selector:
    app: backend
    type: flask
    version: v1
  ports:
    - port: 8080
      targetPort: 8080
