apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  annotations:
    deploymentTool: "This was created by Jenkins on 2020/12/23"
  labels:
    app: backend
    type: flask
    version: v1
spec:
  replicas: 6
  selector:
    matchLabels:
      app: backend
      type: flask
      version: v1
  template:
    metadata:
      labels:
        app: backend
        type: flask
        version: v1
    spec:
      containers:
        - image: public.ecr.aws/v1d1a0v9/flask-simple:latest
          name: flask
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "100m"
              memory: "32Mi"
